id: P003192
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD105923
  title: ཡར་ལྷ་ཤམ་པོའི་གནས་ཡིག་དྭངས་གསལ་མེ་ལོང་།
  author: ''
  volumes:
    3c642fd88ef94427813dd7c1b48a8702:
      image_group_id: I1PD105925
      title: ''
      volume_number: 1
      total_pages: 164
