id: P003192
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 10:46:27.970604
source_metadata:
  id: bdr:W1PD105923
  title: ཡར་ལྷ་ཤམ་པོའི་གནས་ཡིག་དྭངས་གསལ་མེ་ལོང་།
  author: ''
  volumes:
    3c642fd88ef94427813dd7c1b48a8702:
      image_group_id: I1PD105925
      title: ''
      volume_number: 1
      total_pages: 164
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
